name: deploy version ${{ github.ref_name }}

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel twine build

      - name: Build
        run: |
          python -m build .

      - name: Check that package version matches git tag ${{ github.ref_name }}
        shell: bash
        run: |
          ls -l dist
          test -f "dist/napari-plugin-test-${{ github.ref_name }}.tar.gz"
          test -f "dist/napari_plugin_test-${{ github.ref_name }}-py3-none-any.whl"

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
        run: |
          twine upload --verbose --repository testpypi dist/*
